site_name: diffhouse
docs_dir: src
repo_url: https://github.com/vupdivup/diffhouse
repo_name: vupdivup/diffhouse

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - API Reference:
    - Repo: api-reference/repo.md
    - Extractor: api-reference/extractor.md
    - Commit: api-reference/commit.md
    - FileMod: api-reference/filemod.md
    - Diff: api-reference/diff.md
    - Branch: api-reference/branch.md
    - Tag: api-reference/tag.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.expand

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_labels: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            separate_signature: true
            signature_crossrefs: true
            members_order: source
            group_by_category: false
            filters:
              - "!^_"
              - "!^__"
              - "__init__"

markdown_extensions:
  - github-callouts
  - pymdownx.highlight:
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
