site_name: diffhouse
docs_dir: src
repo_url: https://github.com/vupdivup/diffhouse
repo_name: vupdivup/diffhouse

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Benchmarks: benchmarks.md
  - Reference:
    - reference/index.md
    - Repo: reference/repo.md
    - Extractor: reference/extractor.md
    - Commit: reference/commit.md
    - FileMod: reference/filemod.md
    - Diff: reference/diff.md
    - Branch: reference/branch.md
    - Tag: reference/tag.md
    - GitObject: reference/git-object.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.sections
    - navigation.indexes

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_labels: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            separate_signature: true
            signature_crossrefs: true
            members_order: source
            group_by_category: false
            filters:
              - "!^_"
              - "!^__"
              - "__init__"

markdown_extensions:
  - footnotes
  - github-callouts
  - pymdownx.highlight:
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
