name: Test package with minimum supported versions

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 3' # 06:00 UTC every Wednesday

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub API requests

jobs:
  msv-test:
    runs-on: ubuntu-latest
    steps:
      # Install the minimum Git version
      - name: Setup Git (Linux/macOS)
        uses: isikerhan/setup-git@v1
        with:
          git-version: 2.22.0

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ steps.setup-python.outputs.python-version }}

      - name: Install dependencies
        run: >
          uv sync
          --no-default-groups
          --group test
          --resolution lowest-direct
          --all-extras

      - name: Run tests
        run: >
          uv run
          --no-default-groups
          --resolution lowest-direct
          pytest -vv
