name: Test package on multiple OSes

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 3' # 06:00 UTC every Wednesday

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub API requests

jobs:
  os-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      # Use latest Python 3 version
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ steps.setup-python.outputs.python-version }}

      - name: Install dependencies
        run: >
          uv sync no-default-groups
            --group test
            --all-extras

      - name: Run tests
        run: >
          uv run
            --no-default-groups
            pytest -vv
